server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/Артёмина папка/ПРогим/Project/cookadvicer/configsrv/src/main/resources/config/storage,
                            D:/Артёмина папка/ПРогим/Project/cookadvicer/configsrv/src/main/resources/config/auth,
                            D:/Артёмина папка/ПРогим/Project/cookadvicer/configsrv/src/main/resources/config/advisor,
                            D:/Артёмина папка/ПРогим/Project/cookadvicer/configsrv/src/main/resources/config/gateway,
                            D:/Артёмина папка/ПРогим/Project/cookadvicer/configsrv/src/main/resources/config/postman


