zuul:
  prefix: /api
  sensitive-headers: Cookie,Set-Cookie
  routes:
    config:
      path: /config/**
      url: http://localhost:8888


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000